version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: media-downloader-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPPORT_CHAT=${SUPPORT_CHAT}
      - BOT_NAME=${BOT_NAME:-Media Downloader Bot}
      - BOT_OWNER=${BOT_OWNER:-Your Name}
      - HOSTED_AT=${HOSTED_AT:-Sevalla Platform}
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org/bot${BOT_TOKEN}/getMe')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

